variable "deployment_s3_bucket" {}
variable "route53_zone" {}
variable "logfile_s3_bucket" {}
variable "service" {}
variable "enrichment_deployment_s3_root" {}
variable "enrichment_logfile_s3_root" {}
variable "private_record" {}
variable "frontend_deployment_s3_root" {}
variable "frontend_logfile_s3_root" {}
variable "public_domain" {}
variable "region" {}
variable "db_record" {}
variable "cf_dist" {}
variable "internal_domain_name" {}
variable "enrichment_efs_mount_dir" {}
variable "frontend_efs_mount_dir" {}
variable "on_prem_cidrs" {}
variable "redis_efs_mount_dir" {}
