version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.11
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
    labels:
       - "traefik.http.routers.dashbord.rule=Host(`dev-web-frontend.dev.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
       - "traefik.http.routers.api.service=api@internal"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/docker/traefik.yml:/traefik.yml"
    restart: "no"

networks:
  webgateway:
    driver: "bridge"
