# media server - remove July 2026
server {
        listen        80;
        server_name   %{ if environment == "live" }media.nationalarchives.gov.uk nationalarchives.gov.uk%{ else }${environment}-media.nationalarchives.gov.uk%{ endif };

        access_log  /var/log/nginx/media-access.log  main;
        error_log   /var/log/nginx/media-error.log;

        location / {
            return 301 https://webarchive.nationalarchives.gov.uk/ukgwa/20251210105221/https://media.nationalarchives.gov.uk$request_uri;
        }
}
