variable "deployment_s3_bucket" {}
variable "logfile_s3_bucket" {}
variable "service" {}
variable "account_id" {}
variable "foi_s3_bucket" {}
variable "foi_s3_bucket_arn" {}
variable "process_submitted_files_queue_arn" {}
variable "process_submitted_files_queue_url" {}
variable "lambda_web_request_sqs_queue_arn" {}
variable "environment" {}