name: run terraform apply

inputs:
  account:
    description: "The account to run terraform apply for"
    required: true

runs:
  using: "composite"

  steps:
    - name: copy variables
      run: |
        cp ./components/terraform/vars/${{ inputs.account }}/* ./${{ env.working_dir }}/
      shell: bash

    - name: run terraform apply
      run: |
        cd ${{ env.working_dir }}
        terraform init -upgrade

        echo "Running terraform apply (manual approval handled by GitHub environment)"
        terraform apply -auto-approve
      shell: bash
