name: terraform apply

inputs:
  account:
    required: true
    description: "Environment name (dev/staging/live)"

  working_dir:
    required: true
    description: "Terraform working directory"

runs:
  using: "composite"

  steps:
    - name: Copy tfvars
      shell: bash
      run: |
        cp ./components/terraform/vars/${{ inputs.account }}/* ./${{ inputs.working_dir }}/

    - name: Terraform Apply
      shell: bash
      run: |
        cd ${{ inputs.working_dir }}
        terraform apply -auto-approve -input=false tfplan
        