name: Deploy service

inputs:
  config-file:
    required: true
    type: string
  service-name:
    required: true
    type: string
  aws-role:
    required: true
    type: string
  parameter-path:
    required: true
    type: string
  deployed-parameter-path:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: GitHubActionsSession

    - name: Update AWS Parameter Store
      shell: bash
      id: update
      run: |
        echo "Fetching version from config/${{ inputs.config-file }}..."
        NEW_VERSION=$(jq -r ".services.\"${{ inputs.service-name }}\".version" config/${{ inputs.config-file }})
        NEW_IMAGE=$(jq -r ".services.\"${{ inputs.service-name }}\".image" config/${{ inputs.config-file }})

        echo "Updating the AWS Parameter Store..."
        OLD_VALUE=$(aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text)
        NEW_VALUE=$(echo "$OLD_VALUE" | jq --arg new_image "$NEW_IMAGE:$NEW_VERSION" ".\"${{ inputs.service-name }}-application\" = \$new_image")

        echo "Updating /application/web/${{ inputs.service-name }}/docker_images..."
        aws ssm put-parameter --name "${{ inputs.parameter-path }}" --value "$NEW_VALUE" --type String --overwrite

        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"

    - name: Verify the update
      shell: bash
      run: |
        echo "Verifying the updated value..."
        aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text

    - name: Trigger Lambda function
      shell: bash
      run: |
        echo "Triggering lambda function ..."
        VERSION="${{ env.NEW_VERSION }}"
        PAYLOAD=$(jq -n --arg version "$VERSION" '{DEPLOYED_VERSION:$version}')
        RESPONSE=$(aws lambda invoke --function-name AutoRunStartupScript --payload "$PAYLOAD" response.json --log-type Tail --query 'StatusCode' --output text)
        echo "Lambda function response: $RESPONSE"
        cat response.json

        if [[ "$RESPONSE" -ne 200 ]]; then
          echo "Failed to invoke the Lambda function"
          exit 1
        fi

        LAMBDA_ERROR=$(jq -r '.errorMessage' response.json)
        if [[ -n "$LAMBDA_ERROR" ]]; then
          echo "Lambda function error: $LAMBDA_ERROR"
          exit 1
        fi

    - name: Wait for the deployed version to update
      shell: bash
      run: |
        echo "Checking for the deployed version..."
        MAX_RETRIES=20
        RETRY_COUNT=0
        DEPLOYED_VERSION=$(aws ssm get-parameter --name "${{ inputs.deployed-parameter-path }}" --query "Parameter.Value" --output text)
        while [[ "$DEPLOYED_VERSION" != "${{ env.NEW_VERSION }}" ]] && [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
          echo "Current deployed version: $DEPLOYED_VERSION"
          echo "Expected version: ${{ env.NEW_VERSION }}"
          sleep 2
          DEPLOYED_VERSION=$(aws ssm get-parameter --name "${{ inputs.deployed-parameter-path }}" --query "Parameter.Value" --output text)
          RETRY_COUNT=$((RETRY_COUNT+1))
        done
        if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
          echo "Failed to update the deployed version after $MAX_RETRIES attempts"
          exit 1
        fi
        echo "Deployed version updated successfully: $DEPLOYED_VERSION"