name: Deploy service

inputs:
  config-file:
    required: true
    type: string
  service-name:
    required: true
    type: string
  aws-role:
    required: true
    type: string
  parameter-path:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: GitHubActionsSession

    - name: Update AWS Parameter Store
      run: |
        echo "Fetching version from config/${{ inputs.config-file }}..."
        NEW_VERSION=$(jq -r '.services.${{ inputs.service-name }}.version' config/${{ inputs.config-file }})
        NEW_IMAGE=$(jq -r '.services.${{ inputs.service-name }}.image' config/${{ inputs.config-file }})
        echo "Updating the AWS Parameter Store..."
        OLD_VALUE=$(aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text)
        NEW_VALUE=$(echo $OLD_VALUE | jq '."${{ inputs.service-name }}-application" |= "$NEW_IMAGE:$NEW_VERSION"')
        OLD_VERSION=$(jq '."${{ inputs.service-name }}-application"' <<< "$OLD_VALUE")
        NEW_VERSION=$(jq '."${{ inputs.service-name }}-application"' <<< "$NEW_VALUE")
        echo "$OLD_VERSION -> $NEW_VERSION"
        echo "$OLD_VALUE"
        echo "$NEW_VALUE"
        aws ssm put-parameter \
          --name "${{ inputs.parameter-path }}" \
          --value "$NEW_VALUE" \
          --type "String" \
          --overwrite
      shell: bash

    - name: Verify the update
      run: |
        echo "Verifying the update..."
        aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text
      shell: bash
