name: Deploy service

inputs:
  config-file:
    required: true
    type: string
  service-name:
    required: true
    type: string
  aws-role:
    required: true
    type: string
  parameter-path:
    required: true
    type: string
  deployed-parameter-path:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: GitHubActionsSession

    - name: Update AWS Parameter Store
      id: update
      run: |
        echo "Fetching version from config/${{ inputs.config-file }}..."
        NEW_VERSION=$(jq -r '.services.${{ inputs.service-name }}.version' config/${{ inputs.config-file }})
        NEW_IMAGE=$(jq -r '.services.${{ inputs.service-name }}.image' config/${{ inputs.config-file }})

        echo "Updating the AWS Parameter Store..."
        OLD_VALUE=$(aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text)
        NEW_VALUE=$(echo $OLD_VALUE | jq ".\"${{ inputs.service-name }}-application\" |= \"$NEW_IMAGE:$NEW_VERSION\"")

        echo "Updating /application/web/${{ inputs.service-name }}/docker_images..."
        aws ssm put-parameter --name "${{ inputs.parameter-path }}" --value "$NEW_VALUE" --type String --overwrite

        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Verify the update
      run: |
        echo "Verifying the updated value..."
        aws ssm get-parameter --name "${{ inputs.parameter-path }}" --query "Parameter.Value" --output text
      shell: bash

    - name: Wait for the deployed version to update
      run: |
        echo "Checking for the deployed version..."
        MAX_RETIRES=10
        RETRY_COUNT=0
        DEPLOYED_VERSION=$(aws ssm get-parameter --name "${{ inputs.deployed-parameter-path }}" --query "Parameter.Value" --output text)
        while [[ "$DEPLOYED_VERSION" != "${{ env.NEW_VERSION }}" ]] && [[ $RETRY_COUNT -lt $MAX_RETIRES ]]; do
          echo "Current Deployed version: $DEPLOYED_VERSION"
          sleep 2
          DEPLOYED_VERSION=$(aws ssm get-parameter --name "${{ inputs.deployed-parameter-path }}" --query "Parameter.Value" --output text)
          RETRY_COUNT=$((RETRY_COUNT+1))
        done
        if [[ $RETRY_COUNT -eq $MAX_RETIRES ]]; then
          echo "Failed to update the deployed version"
          exit 1
        fi
      shell: bash


