# blog server - remove February 2026
server {
        listen        80;
        server_name   %{ if environment == "live" }blog.nationalarchives.gov.uk nationalarchives.gov.uk%{ else }${environment}-blog.nationalarchives.gov.uk%{ endif };

        access_log  /var/log/nginx/blog-access.log  main;
        error_log   /var/log/nginx/blog-error.log;

        location / {
            return 301 https://webarchive.nationalarchives.gov.uk/ukgwa/20250613000000/https://blog.nationalarchives.gov.uk$request_uri;
        }
}
