# ----------------------------------------------------------------------
# query string redirects
# These redirects are matched against $request_uri because the standard
# redirects.conf uses $uri, which does not include query parameters.
# ----------------------------------------------------------------------

/education/sessions-and-resources/?resource-type=online-workshop    /education/education-sessions/?location=online;
/education/sessions-and-resources/?resource-type=workshop           /education/education-sessions/?location=national_archives;
/education/sessions-and-resources/?resource-type=lesson             /education/teaching-resources/;
/education/sessions-and-resources/?resource-type=themed-collection  /education/teaching-resources/;
/education/sessions-and-resources/?resource-type=focussed-topics    /education/teaching-resources/;
