# Streamline HPP server
server {
        listen        80;
        server_name %{ if environment == "live" }streamline-hpp.nationalarchives.gov.uk%{ else }${environment}-streamline-hpp.nationalarchives.gov.uk%{ endif };

        server_tokens off;
        
        access_log   /var/log/nginx/streamline-hpp-access.log main;
        error_log    /var/log/nginx/streamline-hpp-error.log;

        set_real_ip_from ${set_real_ip_from};
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;

        include cloudfront_ips.conf;
        include variables.conf;
        
        root /var/nationalarchives.gov.uk;  # aws efs
        client_max_body_size 1000M;

        add_header X-Robots-Tag        "noindex, nofollow, nosnippet, noarchive";

        proxy_intercept_errors         off;
        proxy_buffering                off;
        proxy_buffer_size              4k;
        proxy_http_version             1.1;

        proxy_headers_hash_max_size    2048;
        proxy_headers_hash_bucket_size 256;

        proxy_pass_request_headers     on;
        proxy_pass_request_body        on;

        proxy_set_header Host          $host;
        # === TODO: Review start
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header HTTP_X_FORWARDED_PROTO $scheme;
        proxy_set_header HTTP_X_FORWARDED_HOST  $host;
        proxy_set_header X_HOST_TYPE            "public";
        proxy_set_header X-NginX-Proxy          true;
        proxy_set_header Accept-Encoding        "";
        # === Review end

        proxy_redirect $ups_streamline_hpp/    https://$streamline_hpp_base_url/;
       
        ssi on;
        ssi_last_modified on;

        sub_filter_once off;
        subs_filter_types *;
        subs_filter (\/\/|\\\/\\\/)(streamline-hpp\.${environment}\.local) //$base_url gir;
       

        set $base_url   %{ if environment == "live" }streamline-hpp.nationalarchives.gov.uk%{ else }${environment}-streamline-hpp.nationalarchives.gov.uk%{ endif };
        set $streamline_hpp_uri     streamline-hpp.${environment}.local;
        set $ups_streamline_hpp     http://$streamline_hpp_uri;


        location ~* ^/streamlineHPP/(.*)$ {

            proxy_set_header Host $ups_win2016apps_host;
            proxy_pass $ups_win2016apps/streamlineHPP/$1$is_args$args;
        }
    }
