set $wagtail_base_url %{ if environment == "live" }wagtail.nationalarchives.gov.uk%{ else }${environment}-wagtail.nationalarchives.gov.uk%{ endif };
set $root_url   nationalarchives.gov.uk;
set $site_url   www.nationalarchives.gov.uk;
set $base_url   %{ if environment == "live" }www.nationalarchives.gov.uk%{ else }${environment}-www.nationalarchives.gov.uk%{ endif };

set $web_frontend_uri     web-frontend.${environment}.local;
set $web_enrichment_uri   web-enrichment.${environment}.local;
set $web_wagtail_uri     web-wagtail.${environment}.local;
set $web_wagtaildocs_uri  web-wagtaildocs.${environment}.local;
set $web_forms_uri        web-forms.${environment}.local;
set $web_request_service_record_uri  web-rsr.${environment}.local;


set $ups_www          https://$base_url;

set $ups_web_frontend http://$web_frontend_uri;
set $ups_web_enrichment http://$web_enrichment_uri;
set $ups_web_wagtail      http://$web_wagtail_uri;
set $ups_web_wagtaildocs  http://$web_wagtaildocs_uri;
set $ups_web_request_service_record  http://$web_request_service_record_uri;
set $ups_web_forms        http://$web_forms_uri;







# --- ERROR PAGES ---
set $err_page_403 /error_pages/error_403.html;
set $err_page_404 /error_pages/error_404.html;
set $err_page_50x /error_pages/error_500.html;
