# ----------------------------------------------------------------------
# reverse proxy to web-enrichment
# ----------------------------------------------------------------------
    location ~* ^/enrichment/(.*)$ {
        expires 1y;
        access_log off;
        proxy_set_header Host $host;
        proxy_intercept_errors off;
        proxy_set_header x-target "web-enrichment";
        proxy_pass $ups_web_enrichment/enrichment/$1$is_args$args;
    }
