# Web Bulkdownload Locations

    location ~* ^/bulk-download/static/(.*)$ {
        expires 1y;
        access_log off;
        proxy_set_header x-target "web-bulkdownload";
        proxy_pass $ups_web_bulkdownload/bulk-download/static/$1$is_args$args;
    }
    location ~* ^/bulk-download/(.*)$ {
        proxy_set_header Host $host;
        proxy_intercept_errors off;
        proxy_set_header x-target "web-bulkdownload";
        proxy_pass $ups_web_bulkdownload/bulk-download/$1$is_args$args;
    }
    