# ----------------------------------------------------------------------
# reverse proxy to web-hosprec
# ----------------------------------------------------------------------
        location = /hospital-records {
                rewrite ^([^.]*[^/])$ $1/ permanent;
        }
        location ~* ^/hospital-records/(.*)$ {
            expires 1y;
            access_log off;
            proxy_set_header x-target "web-hosprec";
            proxy_pass $ups_web_hosprec/hospital-records/$1$is_args$args;
        }
