# Web Forms Locations

        location = /forms {
                rewrite ^([^.]*[^/])$ $1/ permanent;
        }
        location ~* ^/forms/(.*)$ {
            expires 1y;
            access_log off;
            proxy_set_header x-target "web-forms";
            proxy_pass $ups_web_forms/forms/$1$is_args$args;
        }
        