# /etc/nginx/whitelist.conf
# This file is included in the wagtail_admin.conf to allow access from specific IPs and ranges.
# It is used to restrict access to the Wagtail admin interface.


# Internal TNA IP ranges
allow 10.106.16.0/21;       # corporate wifi
allow 10.128.224.0/23;      # VPN+intersite traffic
allow 85.115.52.0/23;       # Pulse VPN
allow 137.221.134.222/32;   # On-prem
allow 3.172.0.0/16;         # Internal AWS IPs
allow 167.98.93.94/32;      # TNA wifi
allow 137.221.134.224/32;   # Gov wifi

# tna.dblclk.dev
allow 95.217.213.94/32;

# WFH individual IPs
allow 95.144.30.2/32;      # Vaishnavi
allow 109.153.100.149/32;     # AJ
allow 81.100.149.84/32;       # James
allow 82.36.115.56/32;        # Charlie Jones
allow 86.20.99.11/32;         # Helen
allow 84.66.199.181/32;        # Ian jenkins
allow 20.0.202.217/32;        # Curry
allow 10.95.48.0/24;          # AVD range
allow 10.95.52.70/32;         # curry
allow 86.148.111.133/32;      # Simon W
allow 103.7.206.102/32;        # Allan
allow 85.115.53.201/32;       # Maria

allow 193.227.244.5/32;       # Torchbox

allow 86.143.143.148/32;      # Stephanie Scott-Howes
allow 82.148.51.49/32;        # Lauren Pope


# Deny everything else
deny all;
