name: Setup runtime

runs:
  using: "composite"
  steps:
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
    - name: install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
