name: Setup runtime

runs:
  using: "composite"
  steps:
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" 
        architecture: "x64" 
    - name: install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
