name: Copy database to development

on:
  workflow_dispatch:
    inputs:
      source:
        type: choice
        description: Source
        required: true
        default: production
        options:
          - production
          - staging

concurrency:
  group: copy-db-${{ inputs.source }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Copy database to development
        run: |
          echo "Copy ${{ inputs.source }} DB to development"
