name: Compare environments

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source environment
        type: choice
        default: develop
        options:
          - develop
          - staging
      target:
        description: Target environment
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  compare:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.source != github.event.inputs.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Compare develop to staging
        run: |
          echo "## Changes" >> $GITHUB_STEP_SUMMARY
          echo "| Service | Source | Target | Changes |" >> $GITHUB_STEP_SUMMARY
          echo "| ------- | ------ | ------ | ------- |" >> $GITHUB_STEP_SUMMARY
          jq --raw-output '.services | keys[]' "config/${{ github.event.inputs.source }}.json" | while read -r SERVICE_NAME; do SERVICE_SOURCE=$(jq --raw-output --arg service "$SERVICE_NAME" '.services[$service].version' "config/${{ github.event.inputs.source }}.json") && SERVICE_TARGET=$(jq --raw-output --arg service "$SERVICE_NAME" '.services[$service].version' "config/${{ github.event.inputs.target }}.json") && [ "$SERVICE_SOURCE" != "$SERVICE_TARGET" ] && echo "| $SERVICE_NAME | ``$SERVICE_SOURCE`` | ``$SERVICE_TARGET`` | [Compare](https://github.com/nationalarchives/ds-$SERVICE_NAME/compare/v$SERVICE_TARGET...v$SERVICE_SOURCE) |" >> $GITHUB_STEP_SUMMARY || echo "| $SERVICE_NAME | ``$SERVICE_SOURCE`` | ``$SERVICE_TARGET`` | [No changes] |" >> $GITHUB_STEP_SUMMARY; done
