name: Compare dev to staging

on:
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compare develop to staging
        run: |
          SOURCE=develop
          TARGET=staging
          echo "## Changes" >> $GITHUB_STEP_SUMMARY
          echo "\`develop\` -> \`staging\`" >> $GITHUB_STEP_SUMMARY
          echo "| Service | New | Current | Changes |" >> $GITHUB_STEP_SUMMARY
          echo "| ------- | ------ | ------ | ------- |" >> $GITHUB_STEP_SUMMARY
          jq --raw-output '.services | keys[]' "config/$SOURCE.json" | while read -r SERVICE_NAME; do SERVICE_SOURCE=$(jq --raw-output --arg service "$SERVICE_NAME" '.services[$service].version' "config/$SOURCE.json") && SERVICE_TARGET=$(jq --raw-output --arg service "$SERVICE_NAME" '.services[$service].version' "config/$TARGET.json") && [ "$SERVICE_SOURCE" != "$SERVICE_TARGET" ] && echo "| $SERVICE_NAME | \`$SERVICE_TARGET\` | \`$SERVICE_SOURCE\` | [Compare](https://github.com/nationalarchives/ds-$SERVICE_NAME/compare/v$SERVICE_TARGET...v$SERVICE_SOURCE) |" >> $GITHUB_STEP_SUMMARY || echo "| $SERVICE_NAME | \`$SERVICE_SOURCE\` | \`$SERVICE_TARGET\` | [No changes] |" >> $GITHUB_STEP_SUMMARY; done
