name: Release to production

on:
  release:
    types:
      - published

permissions: {}

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  release-variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-number.outputs.VERSION }}
      submitted-by: ${{ steps.submitted-by.outputs.SUBMITTED_BY }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          persist-credentials: false

      - name: Get the release version number
        id: version-number
        run: |
          VERSION=$(echo "${GITHUB_REF}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${GITHUB_REF}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Get the submitted by
        id: submitted-by
        run: |
          SUBMITTED_BY=${GITHUB_ACTOR}
          echo "SUBMITTED_BY=$SUBMITTED_BY"
          echo "SUBMITTED_BY=$SUBMITTED_BY" >> "$GITHUB_OUTPUT"

  notify-approval:
    runs-on: ubuntu-latest
    needs:
      - release-variables
    steps:
      - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_TITLE: Website deployment to production needs approval
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/apple-touch-icon.png
          SLACK_ICON_EMOJI: ":eyes:"
          SLACK_COLOR: #4d91f7
          MSG_MINIMAL: true
          ENABLE_ESCAPES: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: "@here 👀 Release **[v${{ needs.release-variables.outputs.version }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ needs.release-variables.outputs.version }})** needs approval to deploy to production. [Review the workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

  prepare:
    runs-on: ubuntu-latest
    needs:
      - release-variables
      - notify-approval
    environment:
      name: production
      url: https://www.nationalarchives.gov.uk/
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      commit-sha: ${{ steps.copy-config.outputs.COMMIT_SHA }}
      approved-by: ${{ steps.copy-config.outputs.APPROVED_BY }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main

      - name: Copy config from staging to production
        id: copy-config
        run: |
          WORKFLOW_COMMIT_SHA=$(git log --format="%H" -n 1)
          echo "WORKFLOW_COMMIT_SHA=$WORKFLOW_COMMIT_SHA"

          APPROVED_BY=$(gh api "repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/approvals" --jq '.|map(select(.user.type=="User"))|map(.user.login)|join(", ")') || APPROVED_BY=unknown
          echo "APPROVED_BY=$APPROVED_BY"
          echo "APPROVED_BY=$APPROVED_BY" >> "$GITHUB_OUTPUT"

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "<>"
          cp config/staging.json config/production.json
          git add config/production.json
          git commit -m "Release v$VERSION to production" || true
          git push
          COMMIT_SHA=$(git log --format="%H" -n 1)
          echo "COMMIT_SHA=$COMMIT_SHA"
          echo "COMMIT_SHA=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          VERSION: ${{ needs.release-variables.outputs.version }}

  notify-start:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - release-variables
    steps:
      - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_TITLE: Website deployment
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/apple-touch-icon.png
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: #888888
          MSG_MINIMAL: true
          ENABLE_ESCAPES: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: "🚀 Release **[v${{ needs.release-variables.outputs.version }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ needs.release-variables.outputs.version }})** deploying to production... *(approved by ${{ needs.prepare.outputs.approved-by }})*"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        service:
          - frontend
          - enrichment
          - wagtail
          - catalogue
          - search
          - wagtaildocs
          - requestservicerecord
          - bulkdownload
    timeout-minutes: 15
    permissions:
      id-token: write
      packages: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ needs.prepare.outputs.commit-sha }}
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::968803923593:role/github-oidc-Role-1QSZDDE2NZQV0
          role-session-name: GitHubActionsSession

      - name: Update SSM parameters
        uses: ./.github/actions/update-environment-variables
        with:
          service-name: ${{ matrix.service }}
          environment: production
          parameter-path: /application/web/${{ matrix.service }}

      - name: Deploy service
        uses: ./.github/actions/deploy
        with:
          config-file: production.json
          service-name: ${{ matrix.service }}
          parameter-path: /application/web/${{ matrix.service }}/docker_images
          deployed-parameter-path: /application/web/${{ matrix.service }}/deployed_version

  notify-end-status:
    runs-on: ubuntu-latest
    needs:
      - release-variables
      - deploy
    if: ${{ !cancelled() }}
    steps:
      - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        if: ${{ needs.deploy.result == 'success' }}
        env:
          SLACK_TITLE: Website deployment
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/apple-touch-icon.png
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: success
          MSG_MINIMAL: true
          ENABLE_ESCAPES: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: "🎉 Release **[v${{ needs.release-variables.outputs.version }}](https://github.com/nationalarchives/ds-infrastructure-web/releases/tag/v${{ needs.release-variables.outputs.version }})** deployed to production: [www.nationalarchives.gov.uk](http://www.nationalarchives.gov.uk/)"

      - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        if: ${{ needs.deploy.result != 'success' }}
        env:
          SLACK_TITLE: Website deployment
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/apple-touch-icon.png
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: failure
          MSG_MINIMAL: true
          ENABLE_ESCAPES: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: "❌ Release **[v${{ needs.release-variables.outputs.version }}](https://github.com/nationalarchives/ds-infrastructure-web/releases/tag/v${{ needs.release-variables.outputs.version }})** failed to deploy to production"

  tests:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - deploy
    env:
      GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN_TEST_RUNNER }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ needs.prepare.outputs.commit-sha }}
          persist-credentials: false

      - name: Run tests
        run: |
          gh workflow run run.yml --repo nationalarchives/ds-tna-website-tests --field environment=production --raw-field exclude-tests="@wip" --field notify-slack-on-pass=true --field notify-slack-on-fail=true --raw-field description="$(git log -1 --pretty=%B | sed '/./,$!d' | sed '/^$/d' | sed 's/^/> /')"
          sleep 5
          gh run watch --exit-status --repo nationalarchives/ds-tna-website-tests $(gh run list --repo nationalarchives/ds-tna-website-tests --workflow run.yml -L1 --json databaseId --jq .[0].databaseId)
