---
name: Nginx Config Plan

permissions:
      id-token: write
      contents: write

on:
  workflow_call:
    inputs:
      deploy-environment:
        type: string
        required: true
      github-environment:
        type: string
        required: true
      account_id:
        type: string
        required: true
      role-to-assume:
        type: string
        required: true
      branch:
        type: string
        required: false
        default: ""

jobs:
   terraform:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      env:
          environment: "${{ inputs.deploy-environment }}"
          working-directory: components/terraform
          account_id: "${{ inputs.account_id }}"
          region: eu-west-2
      steps:
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
            with:
                aws-region: eu-west-2
                role-to-assume: "${{ inputs.role-to-assume }}"
                role-session-name: github-actions-session

          - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
            with:
              python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
              architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

          - name: Checkout
            uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            with:
              ref: ${{ env.branch }}
              persist-credentials: false

          - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3

          - name: Check Python
            run: |
              python --version

          - name: Create Backend S3 Bucket
            run: |
              if 
               aws s3 ls "s3://tna-terraform-web-backend-state-${{ env.region }}-${{ env.account_id }}" 2>&1 | grep -q 'NoSuchBucket' 
              then 
               aws s3api create-bucket \
                  --bucket tna-terraform-web-backend-state-${{ env.region }}-${{ env.account_id }} \
                  --region ${{ env.region }} \
                  --create-bucket-configuration LocationConstraint=${{ env.region }}

               aws s3api put-public-access-block \
                  --bucket tna-terraform-web-backend-state-${{ env.region }}-${{ env.account_id }} \
                  --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
              else
               echo 'Bucket Already Exists'
              fi

          - name: Copy Environment Vars
            run: |
              echo 'test'
              cp ./components/terraform/vars/${{ env.environment }}/* ./components/terraform/

          - name: Terraform init
            id: init
            run: terraform init -upgrade
            working-directory: ${{ env.working-directory }}

          - name: Terraform Plan
            id: plan
            run: terraform plan -target module.nginx_conf
            working-directory: ${{ env.working-directory }}