name: TF scheduled apply infrastructure

on:
  schedule:
    - cron: '45 12 * * 5'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - account: dev
            role: arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL
            environment: dev

          # - account: staging
          #   role: arn:aws:iam::337670467269:role/GitHubActionRole
          #   environment: staging

          # - account: live
          #   role: arn:aws:iam::968803923593:role/github-oidc-Role-1QSZDDE2NZQV0
          #   environment: production

    environment: ${{ matrix.environment }}

    env:
      working_dir: components/terraform

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ matrix.role }}
          role-session-name: MySessionName

      - name: Setup runner
        uses: ./.github/actions/setup-runtime

      # ---------------- PLAN ----------------
      - name: Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          account: ${{ matrix.account }}

      # ---------------- SLACK ----------------
      - name: Get Slack credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: infrastructure/ds-infrastructure-notifications/slack
          parse-json-secrets: true

      - name: Slack notify
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ env.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL_ID }}
            text: ":warning: *${{ matrix.account }} Terraform plan completed*\nApproval required before APPLY\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      # ---------------- APPLY ----------------
      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          account: ${{ matrix.account }}