---
name: Terraform Plan Dev
run-name: terraform plan for ds-infrastructure-web by @${{ github.actor }}

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  # push:  # TODO: Re-enable once ready
  #   branches:
  #     - main

jobs:
  terraform-plan-dev:
    uses: nationalarchives/ds-github-actions/.github/workflows/terraform-plan.yml@main
    with:
      assume_role: "arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL"
      region: "eu-west-2"
      account: "dev"
# ------------------------------------------------------------------------------

