name: Run tests

on:
  workflow_dispatch:
    inputs:
      domain:
        type: string
        description: Domain to test
        required: true
        default: "https://develop.tna.dblclk.dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/test
        with:
          domain: ${{ inputs.domain }}
