name: Update Frontend Image Version

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        default: "develop"
        options:
          - develop
          - staging
          - live

jobs:
  update-frontend-image-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GITHUB_OIDC_ROLE }}
     
      - name: Get the current value from Parameter Store
        id: get_param
        run: |
          aws ssm get-parameter --name /application/web/frontend/docker_images --query "Parameter.Value" --output text > current_value.json

      - name: Extract current version from current value
        id: extract_version
        run: |
          CURRENT_VERSION=$(jq -r '.["frontend-application"]' current_value.json | sed -e 's/^.*://')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Update the image version
        id: update_version
        run: |
          # Extract new version from the config based on the selected environment
          NEW_VERSION=$(jq -r ".services.frontend.version" config/${{ inputs.deploy-environment }}.json)
          UPDATED_VALUE=$(jq ".\"frontend-application\" |= \"ghcr.io/nationalarchives/ds-frontend:$NEW_VERSION\"" current_value.json)

          # Update the parameter in AWS Parameter Store
          aws ssm put-parameter \
            --name /application/web/frontend/docker_images \
            --value "$UPDATED_VALUE" \
            --type String \
            --overwrite

      - name: Verify the update
        run: |
          aws ssm get-parameter --name /application/web/frontend/docker_images --query "Parameter.Value" --output text